src/FrontEnd/ECommerce.WebUI/Controllers/Others/AppRoleController.cs
using ECommerce.EntityLayer.Concrete;
using ECommerce.WebUI.Dtos.AppRoleDto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NuGet.Versioning;

namespace ECommerce.WebUI.Controllers.Others
{
    [Authorize(Roles = "Admin")]
    public class AppRoleController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;

        public AppRoleController(RoleManager<AppRole> roleManager)
        {
            _roleManager = roleManager;
        }
        //------------------------------------------------------------------------------------------------------------------------------
        public IActionResult Index()
        {
            var values = _roleManager.Roles.ToList();
            return View(values);
        }
        //------------------------------------------------------------------------------------------------------------------------------
        [HttpGet]
        public IActionResult AddAppRole()
        {
            return View();
        }
        //------------------------------------------------------------------------------------------------------------------------------
        [HttpPost]
        public async Task<IActionResult> AddAppRole(CreateAppRoleDto createAppRoleDto)
        {
            AppRole role = new AppRole()
            {
                Name = createAppRoleDto.AppRoleName
            };
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View(result);
        }
        //------------------------------------------------------------------------------------------------------------------------------
        [HttpGet]
        public async Task<IActionResult> UpdateAppRole(int id)
        {
            var yakaladigimDbdekiRol = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            UpdateAppRoleDto updatemodel = new UpdateAppRoleDto()
            {
                RoleId = yakaladigimDbdekiRol.Id,
                AppRoleName = yakaladigimDbdekiRol.Name,
            };
            return View(updatemodel);
        }
        //------------------------------------------------------------------------------------------------------------------------------
        [HttpPost]
        public async Task<IActionResult> UpdateAppRole(UpdateAppRoleDto updatemodel)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == updatemodel.RoleId);
            values.Name = updatemodel.AppRoleName;
            await _roleManager.UpdateAsync(values);
            return RedirectToAction("Index");
        }
        //------------------------------------------------------------------------------------------------------------------------------
        public async Task<IActionResult> DeleteAppRole(int id)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            await _roleManager.DeleteAsync(values);
            return RedirectToAction("Index");
        }
        //------------------------------------------------------------------------------------------------------------------------------


    }
}

src/FrontEnd/ECommerce.WebUI/Views/AppRole/AddAppRole.cshtml
@model ECommerce.WebUI.Dtos.AppRoleDto.CreateAppRoleDto
@{
    ViewData["Title"] = "AddAppRole";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}

-<form method="post" asp-controller="AppRole" asp-action="AddAppRole">

    <label>Rol Adını Giriniz</label>
    <input type="text" asp-for="AppRoleName" class="form-control" />
    
    <br />
    <button class="btn btn-primary">Yeni Rol Ekle</button>

</form>

src/FrontEnd/ECommerce.WebUI/Views/AppRole/Index.cshtml
@model List<ECommerce.EntityLayer.Concrete.AppRole>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}

<h1>Rol Listesi</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Rol Adı</th>
        <th>Güncelle</th>
        <th>Sil</th>
        

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td> <a href="/AppRole/UpdateAppRole/@item.Id" class="btn btn-info"><strong>Güncelle</strong></a></td>
            <td> <a href="/AppRole/DeleteAppRole/@item.Id" class="btn btn-outline-danger"><strong>Sil</strong></a></td>          
        </tr>
    }
</table>
<a href="/AppRole/AddAppRole/" class="btn btn-info">Yeni Rol Ekle</a>

src/FrontEnd/ECommerce.WebUI/Views/AppRole/UpdateAppRole.cshtml
@model ECommerce.WebUI.Dtos.AppRoleDto.UpdateAppRoleDto
@{
    ViewData["Title"] = "UpdateAppRole";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}

<h1>Role Güncelle</h1>
<form method="post" asp-controller="AppRole" asp-action="UpdateAppRole">

    <input type="hidden" asp-for="RoleId" />

    <label>Rol Adını Giriniz</label>
    <input type="text" asp-for="AppRoleName" class="form-control" />

    <br />
    <button class="btn btn-primary">Rol Güncelle</button>

</form>